version: '3'
services:
  db:
    container_name: 'mud-db'
    image: postgres
    environment:
      POSTGRES_USER: mudDB
      POSTGRES_PASSWORD: pgSecret
    ports:
      - 5412:5432
    networks:
      - laravel_network
  admin:
    container_name: 'mud-admin'
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: stevewe@me.com
      PGADMIN_DEFAULT_PASSWORD: pgSecret
    ports:
      - 9011:80
    networks:
      - laravel_network
  mailhog:
    container_name: 'mud-hog'
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - laravel_network
networks:
  laravel_network:
    driver: bridge